// frontend/react/src/ui/states.tsx
import type { ReactNode } from "react";

/** Os quatro estados que toda tela que busca dados precisa tratar. */

export function Loading({ label = "Carregando…" }: { label?: string }) {
  return (
    <p role="status" className="py-10 text-center text-sm text-stone-500">
      {label}
    </p>
  );
}

export function Empty({ children }: { children: ReactNode }) {
  return (
    <p className="rounded border border-dashed border-stone-300 py-10 text-center text-sm text-stone-500">
      {children}
    </p>
  );
}

export function Failed({ message, onRetry }: { message: string; onRetry?: () => void }) {
  return (
    <div role="alert" className="rounded border border-red-300 bg-red-50 px-4 py-6 text-center">
      <p className="text-sm text-red-800">{message}</p>
      {onRetry ? (
        <button onClick={onRetry} className="mt-3 text-sm font-medium text-red-900 underline">
          Tentar de novo
        </button>
      ) : null}
    </div>
  );
}

// frontend/angular/src/ui/states.component.ts
import { ChangeDetectionStrategy, Component, input, output } from "@angular/core";

/** Os quatro estados que toda tela que busca dados precisa tratar. */

@Component({
  selector: "app-loading",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<p role="status" class="py-10 text-center text-sm text-stone-500">{{ label() }}</p>`,
})
export class LoadingComponent {
  readonly label = input("Carregando…");
}

@Component({
  selector: "app-empty",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <p
      class="rounded border border-dashed border-stone-300 py-10 text-center text-sm text-stone-500"
    >
      <ng-content />
    </p>
  `,
})
export class EmptyComponent {}

@Component({
  selector: "app-failed",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div role="alert" class="rounded border border-red-300 bg-red-50 px-4 py-6 text-center">
      <p class="text-sm text-red-800">{{ message() }}</p>
      @if (retryable()) {
        <button class="mt-3 text-sm font-medium text-red-900 underline" (click)="retry.emit()">
          Tentar de novo
        </button>
      }
    </div>
  `,
})
export class FailedComponent {
  readonly message = input.required<string>();
  readonly retryable = input(false);
  readonly retry = output();
}
