// frontend/vue/src/app/pages/MePage.vue
<script setup lang="ts">
import { messageOf } from "@/domain/problem";
import { initialsOf } from "@/domain/user";
import { useCurrentUser } from "@/features/auth/use-auth";
import AppFailed from "@/ui/AppFailed.vue";
import AppLoading from "@/ui/AppLoading.vue";

const me = useCurrentUser();
</script>

<template>
  <AppLoading v-if="me.isPending.value" />
  <AppFailed
    v-else-if="me.isError.value"
    :message="messageOf(me.error.value)"
    retryable
    @retry="me.refetch()"
  />

  <section v-else-if="me.data.value">
    <h1 class="mb-6 text-2xl font-semibold">Meu perfil</h1>
    <div class="flex items-center gap-4 rounded border border-stone-200 bg-white p-6">
      <span
        aria-hidden="true"
        class="grid size-12 place-items-center rounded-full bg-stone-200 text-lg font-semibold text-stone-600"
      >
        {{ initialsOf(me.data.value) }}
      </span>
      <dl class="text-sm">
        <dt class="sr-only">Nome</dt>
        <dd class="font-medium">{{ me.data.value.name }}</dd>
        <dt class="sr-only">E-mail</dt>
        <dd class="text-stone-600">{{ me.data.value.email }}</dd>
      </dl>
    </div>
  </section>
</template>

// frontend/react/src/app/pages/me-page.tsx
import { messageOf } from "@/domain/problem";
import { initialsOf } from "@/domain/user";
import { useCurrentUser } from "@/features/auth/use-auth";
import { Failed, Loading } from "@/ui/states";

export function MePage() {
  const me = useCurrentUser();

  if (me.isPending) return <Loading />;
  if (me.isError) return <Failed message={messageOf(me.error)} onRetry={() => void me.refetch()} />;

  return (
    <section>
      <h1 className="mb-6 text-2xl font-semibold">Meu perfil</h1>
      <div className="flex items-center gap-4 rounded border border-stone-200 bg-white p-6">
        <span
          aria-hidden
          className="grid size-12 place-items-center rounded-full bg-stone-200 text-lg font-semibold text-stone-600"
        >
          {initialsOf(me.data)}
        </span>
        <dl className="text-sm">
          <dt className="sr-only">Nome</dt>
          <dd className="font-medium">{me.data.name}</dd>
          <dt className="sr-only">E-mail</dt>
          <dd className="text-stone-600">{me.data.email}</dd>
        </dl>
      </div>
    </section>
  );
}
