// frontend/vue/src/app/pages/NewUserPage.vue
<script setup lang="ts">
import { toTypedSchema } from "@vee-validate/zod";
import { useForm } from "vee-validate";
import { computed } from "vue";
import { useRouter } from "vue-router";
import { z } from "zod";
import { fieldErrorsOf, firstMessage, messageOf } from "@/domain/problem";
import { useCreateUser } from "@/features/users/use-users";
import AppAlert from "@/ui/AppAlert.vue";
import AppButton from "@/ui/AppButton.vue";
import AppField from "@/ui/AppField.vue";

const schema = toTypedSchema(
  z.object({
    name: z.string().min(1, "Informe o nome"),
    email: z.string().min(1, "Informe o e-mail").email("Formato de e-mail inválido"),
    password: z.string().min(12, "A senha precisa de ao menos 12 caracteres"),
  }),
);

const { handleSubmit, errors, defineField } = useForm({ validationSchema: schema });
const [name] = defineField("name");
const [email] = defineField("email");
const [password] = defineField("password");

const createUser = useCreateUser();
const router = useRouter();
const serverErrors = computed(() => fieldErrorsOf(createUser.error.value));
const hasGeneralError = computed(
  () => createUser.isError.value && Object.keys(serverErrors.value).length === 0,
);

const onSubmit = handleSubmit((values) => {
  createUser.mutate(values, { onSuccess: () => void router.push("/users") });
});
</script>

<template>
  <section class="max-w-sm">
    <h1 class="mb-6 text-2xl font-semibold">Novo usuário</h1>

    <form novalidate class="flex flex-col gap-4" @submit="onSubmit">
      <AppField v-model="name" label="Nome" :error="firstMessage(errors.name, serverErrors['name'])" />
      <AppField
        v-model="email"
        label="E-mail"
        type="email"
        :error="firstMessage(errors.email, serverErrors['email'])"
      />
      <AppField
        v-model="password"
        label="Senha"
        type="password"
        autocomplete="new-password"
        :error="firstMessage(errors.password, serverErrors['password'])"
      />

      <AppAlert v-if="hasGeneralError" tone="error">{{ messageOf(createUser.error.value) }}</AppAlert>

      <div class="flex gap-3">
        <AppButton type="submit" :loading="createUser.isPending.value">Salvar</AppButton>
        <AppButton type="button" variant="ghost" @click="router.push('/users')">Voltar</AppButton>
      </div>
    </form>
  </section>
</template>

// frontend/react/src/app/pages/new-user-page.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { useNavigate } from "react-router";
import { z } from "zod";
import { fieldErrorsOf, firstMessage, messageOf } from "@/domain/problem";
import { useCreateUser } from "@/features/users/use-users";
import { Alert } from "@/ui/alert";
import { Button } from "@/ui/button";
import { Field } from "@/ui/field";

const schema = z.object({
  name: z.string().min(1, "Informe o nome"),
  email: z.string().min(1, "Informe o e-mail").email("Formato de e-mail inválido"),
  password: z.string().min(12, "A senha precisa de ao menos 12 caracteres"),
});

export function NewUserPage() {
  const createUser = useCreateUser();
  const navigate = useNavigate();
  const { register, handleSubmit, formState } = useForm<z.infer<typeof schema>>({
    resolver: zodResolver(schema),
  });

  const serverErrors = fieldErrorsOf(createUser.error);

  return (
    <section className="max-w-sm">
      <h1 className="mb-6 text-2xl font-semibold">Novo usuário</h1>

      <form
        noValidate
        className="flex flex-col gap-4"
        onSubmit={(event) => {
          void handleSubmit((values) => {
            createUser.mutate(values, { onSuccess: () => void navigate("/users") });
          })(event);
        }}
      >
        <Field
          label="Nome"
          error={firstMessage(formState.errors.name?.message, serverErrors["name"])}
          {...register("name")}
        />
        <Field
          label="E-mail"
          type="email"
          error={firstMessage(formState.errors.email?.message, serverErrors["email"])}
          {...register("email")}
        />
        <Field
          label="Senha"
          type="password"
          autoComplete="new-password"
          error={firstMessage(formState.errors.password?.message, serverErrors["password"])}
          {...register("password")}
        />

        {createUser.isError && Object.keys(serverErrors).length === 0 ? (
          <Alert tone="error">{messageOf(createUser.error)}</Alert>
        ) : null}

        <div className="flex gap-3">
          <Button type="submit" loading={createUser.isPending}>
            Salvar
          </Button>
          <Button
            type="button"
            variant="ghost"
            onClick={() => {
              void navigate("/users");
            }}
          >
            Voltar
          </Button>
        </div>
      </form>
    </section>
  );
}
