// frontend/vue/src/app/pages/UserDetailPage.vue
<script setup lang="ts">
import { toTypedSchema } from "@vee-validate/zod";
import { useForm } from "vee-validate";
import { computed, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { z } from "zod";
import { fieldErrorsOf, firstMessage, isNotFound, messageOf } from "@/domain/problem";
import { useUpdateUser, useUser } from "@/features/users/use-users";
import AppAlert from "@/ui/AppAlert.vue";
import AppButton from "@/ui/AppButton.vue";
import AppField from "@/ui/AppField.vue";
import AppFailed from "@/ui/AppFailed.vue";
import AppLoading from "@/ui/AppLoading.vue";

const route = useRoute();
const router = useRouter();
const id = computed(() => String(route.params["id"] ?? ""));

const user = useUser(id);
const update = useUpdateUser(id);

const schema = toTypedSchema(
  z.object({
    name: z.string().min(1, "Informe o nome"),
    email: z.string().min(1, "Informe o e-mail").email("Formato de e-mail inválido"),
  }),
);

const { handleSubmit, errors, defineField, setValues } = useForm({ validationSchema: schema });
const [name] = defineField("name");
const [email] = defineField("email");

watch(
  () => user.data.value,
  (loaded) => {
    if (loaded) setValues({ name: loaded.name, email: loaded.email });
  },
  { immediate: true },
);

const serverErrors = computed(() => fieldErrorsOf(update.error.value));
const hasGeneralError = computed(
  () => update.isError.value && Object.keys(serverErrors.value).length === 0,
);
const notFound = computed(() => isNotFound(user.error.value));

const onSubmit = handleSubmit((values) => {
  update.mutate(values);
});
</script>

<template>
  <AppLoading v-if="user.isPending.value" />
  <AppFailed v-else-if="notFound" message="Usuário não encontrado." />
  <AppFailed
    v-else-if="user.isError.value"
    :message="messageOf(user.error.value)"
    retryable
    @retry="user.refetch()"
  />

  <section v-else class="max-w-sm">
    <h1 class="mb-6 text-2xl font-semibold">Editar usuário</h1>

    <form novalidate class="flex flex-col gap-4" @submit="onSubmit">
      <AppField
        v-model="name"
        label="Nome"
        :error="firstMessage(errors.name, serverErrors['name'])"
      />
      <AppField
        v-model="email"
        label="E-mail"
        type="email"
        :error="firstMessage(errors.email, serverErrors['email'])"
      />

      <AppAlert v-if="update.isSuccess.value" tone="success">Alterações salvas.</AppAlert>
      <AppAlert v-if="hasGeneralError" tone="error">{{ messageOf(update.error.value) }}</AppAlert>

      <div class="flex gap-3">
        <AppButton type="submit" :loading="update.isPending.value">Salvar</AppButton>
        <AppButton type="button" variant="ghost" @click="router.push('/users')">Voltar</AppButton>
      </div>
    </form>
  </section>
</template>

// frontend/react/src/app/pages/user-detail-page.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { useNavigate, useParams } from "react-router";
import { z } from "zod";
import { fieldErrorsOf, firstMessage, isNotFound, messageOf } from "@/domain/problem";
import { useUpdateUser, useUser } from "@/features/users/use-users";
import { Alert } from "@/ui/alert";
import { Button } from "@/ui/button";
import { Field } from "@/ui/field";
import { Failed, Loading } from "@/ui/states";

const schema = z.object({
  name: z.string().min(1, "Informe o nome"),
  email: z.string().min(1, "Informe o e-mail").email("Formato de e-mail inválido"),
});

function LoadFailure({ error, onRetry }: { error: unknown; onRetry: () => void }) {
  if (isNotFound(error)) return <Failed message="Usuário não encontrado." />;
  return <Failed message={messageOf(error)} onRetry={onRetry} />;
}

export function UserDetailPage() {
  const { id = "" } = useParams();
  const navigate = useNavigate();
  const user = useUser(id);
  const update = useUpdateUser(id);

  const { register, handleSubmit, formState, reset } = useForm<z.infer<typeof schema>>({
    resolver: zodResolver(schema),
  });

  useEffect(() => {
    if (user.data) reset({ name: user.data.name, email: user.data.email });
  }, [user.data, reset]);

  const serverErrors = fieldErrorsOf(update.error);

  if (user.isPending) return <Loading />;
  if (user.isError) return <LoadFailure error={user.error} onRetry={() => void user.refetch()} />;

  return (
    <section className="max-w-sm">
      <h1 className="mb-6 text-2xl font-semibold">Editar usuário</h1>

      <form
        noValidate
        className="flex flex-col gap-4"
        onSubmit={(event) => {
          void handleSubmit((values) => {
            update.mutate(values);
          })(event);
        }}
      >
        <Field
          label="Nome"
          error={firstMessage(formState.errors.name?.message, serverErrors["name"])}
          {...register("name")}
        />
        <Field
          label="E-mail"
          type="email"
          error={firstMessage(formState.errors.email?.message, serverErrors["email"])}
          {...register("email")}
        />

        {update.isSuccess ? <Alert tone="success">Alterações salvas.</Alert> : null}
        {update.isError && Object.keys(serverErrors).length === 0 ? (
          <Alert tone="error">{messageOf(update.error)}</Alert>
        ) : null}

        <div className="flex gap-3">
          <Button type="submit" loading={update.isPending}>
            Salvar
          </Button>
          <Button
            type="button"
            variant="ghost"
            onClick={() => {
              void navigate("/users");
            }}
          >
            Voltar
          </Button>
        </div>
      </form>
    </section>
  );
}
