// frontend/react/src/app/pages/new-user-page.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { useNavigate } from "react-router";
import { z } from "zod";
import { fieldErrorsOf, firstMessage, messageOf } from "@/domain/problem";
import { useCreateUser } from "@/features/users/use-users";
import { Alert } from "@/ui/alert";
import { Button } from "@/ui/button";
import { Field } from "@/ui/field";

const schema = z.object({
  name: z.string().min(1, "Informe o nome"),
  email: z.string().min(1, "Informe o e-mail").email("Formato de e-mail inválido"),
  password: z.string().min(12, "A senha precisa de ao menos 12 caracteres"),
});

export function NewUserPage() {
  const createUser = useCreateUser();
  const navigate = useNavigate();
  const { register, handleSubmit, formState } = useForm<z.infer<typeof schema>>({
    resolver: zodResolver(schema),
  });

  const serverErrors = fieldErrorsOf(createUser.error);

  return (
    <section className="max-w-sm">
      <h1 className="mb-6 text-2xl font-semibold">Novo usuário</h1>

      <form
        noValidate
        className="flex flex-col gap-4"
        onSubmit={(event) => {
          void handleSubmit((values) => {
            createUser.mutate(values, { onSuccess: () => void navigate("/users") });
          })(event);
        }}
      >
        <Field
          label="Nome"
          error={firstMessage(formState.errors.name?.message, serverErrors["name"])}
          {...register("name")}
        />
        <Field
          label="E-mail"
          type="email"
          error={firstMessage(formState.errors.email?.message, serverErrors["email"])}
          {...register("email")}
        />
        <Field
          label="Senha"
          type="password"
          autoComplete="new-password"
          error={firstMessage(formState.errors.password?.message, serverErrors["password"])}
          {...register("password")}
        />

        {createUser.isError && Object.keys(serverErrors).length === 0 ? (
          <Alert tone="error">{messageOf(createUser.error)}</Alert>
        ) : null}

        <div className="flex gap-3">
          <Button type="submit" loading={createUser.isPending}>
            Salvar
          </Button>
          <Button
            type="button"
            variant="ghost"
            onClick={() => {
              void navigate("/users");
            }}
          >
            Voltar
          </Button>
        </div>
      </form>
    </section>
  );
}

// frontend/angular/src/app/pages/new-user.page.ts
import { ChangeDetectionStrategy, Component, inject, signal } from "@angular/core";
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from "@angular/forms";
import { Router } from "@angular/router";
import { fieldErrorsOf, firstMessage, messageOf } from "../../domain/problem";
import { UsersService } from "../../features/users/users.service";
import { AlertComponent } from "../../ui/alert.component";
import { ButtonComponent } from "../../ui/button.component";
import { FieldComponent } from "../../ui/field.component";
import { controlError } from "../form-errors";

@Component({
  selector: "app-new-user-page",
  imports: [ReactiveFormsModule, AlertComponent, ButtonComponent, FieldComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="max-w-sm">
      <h1 class="mb-6 text-2xl font-semibold">Novo usuário</h1>

      <form novalidate class="flex flex-col gap-4" [formGroup]="form" (ngSubmit)="submit()">
        <app-field
          label="Nome"
          fieldId="new-user-name"
          [control]="form.controls.name"
          [error]="error('name', 'Informe o nome')"
        />
        <app-field
          label="E-mail"
          fieldId="new-user-email"
          type="email"
          [control]="form.controls.email"
          [error]="error('email', 'Informe o e-mail', 'Formato de e-mail inválido')"
        />
        <app-field
          label="Senha"
          fieldId="new-user-password"
          type="password"
          autocomplete="new-password"
          [control]="form.controls.password"
          [error]="
            error('password', 'Informe a senha', 'A senha precisa de ao menos 12 caracteres')
          "
        />

        @if (generalError(); as message) {
          <app-alert tone="error">{{ message }}</app-alert>
        }

        <div class="flex gap-3">
          <app-button type="submit" [loading]="pending()">Salvar</app-button>
          <app-button type="button" variant="ghost" (click)="voltar()">Voltar</app-button>
        </div>
      </form>
    </section>
  `,
})
export class NewUserPage {
  private readonly users = inject(UsersService);
  private readonly router = inject(Router);

  protected readonly form = new FormGroup({
    name: new FormControl("", { nonNullable: true, validators: [Validators.required] }),
    email: new FormControl("", {
      nonNullable: true,
      validators: [Validators.required, Validators.email],
    }),
    password: new FormControl("", {
      nonNullable: true,
      validators: [Validators.required, Validators.minLength(12)],
    }),
  });

  protected readonly pending = signal(false);
  protected readonly failure = signal<unknown>(null);

  protected error(field: "name" | "email" | "password", required: string, invalid?: string) {
    return firstMessage(
      controlError(this.form.controls[field], required, invalid),
      fieldErrorsOf(this.failure())[field],
    );
  }

  protected generalError(): string | undefined {
    const failure = this.failure();
    if (!failure || Object.keys(fieldErrorsOf(failure)).length > 0) return undefined;
    return messageOf(failure);
  }

  protected voltar(): void {
    void this.router.navigate(["/users"]);
  }

  protected async submit(): Promise<void> {
    this.form.markAllAsTouched();
    if (this.form.invalid) return;

    this.pending.set(true);
    this.failure.set(null);
    try {
      await this.users.create(this.form.getRawValue());
      await this.router.navigate(["/users"]);
    } catch (error) {
      this.failure.set(error);
    } finally {
      this.pending.set(false);
    }
  }
}
